# Generated by Django 3.2.7 on 2021-10-04 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='league',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('game_code', models.CharField(max_length=1000)),
                ('starting_balance', models.IntegerField()),
                ('users', models.ManyToManyField(related_name='league', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
