# Generated by Django 3.2.7 on 2021-10-18 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='simulator.league'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='simulator.league'),
            preserve_default=False,
        ),
    ]
