# Generated by Django 3.2.7 on 2021-10-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_auto_20211018_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
