# Generated by Django 3.2.7 on 2021-10-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0010_remove_holdings_total_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lauth',
            name='balance',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
    ]
