# Generated by Django 3.2.7 on 2021-10-20 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0013_alter_transfer_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holdings',
            options={'verbose_name_plural': 'Holdings'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='stocks',
            options={'verbose_name_plural': 'Stocks'},
        ),
    ]
