# Generated by Django 3.2.7 on 2021-10-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0015_auto_20211023_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
